tools_list = [
    ".NET", "Adobe XD", "Airflow", "Alamofire", "Alexa Skills Kit", "Amplify", "Ansible",
    "Apache", "Apache Kafka", "Apache Airflow", "Apache NiFi", "Apache Storm", "AppDynamics",
    "Argo", "Asana", "Athena", "AWS", "AWS SageMaker", "Azure", "Azure DevOps", "Azure ML",
    "Bash", "BigQuery", "Bizagi", "Bitbucket", "Blender", "Bootstrap", "C++", "Caffe",
    "Cassandra", "Chef", "Cisco ASA", "Cisco Packet Tracer", "CircleCI", "ClickHouse",
    "CloudFormation", "CloudWatch", "Combine", "Confluence", "CoreData", "CSS", "Dagger",
    "DataRobot", "Databricks", "Datadog", "dbt (data build tool)", "Django", "Docker",
    "Docker Swarm", "Domo", "Draw.io", "Dynatrace", "Eclipse", "ElasticSearch", "Excel",
    "Fargate", "FastAPI", "Firebase", "Figma", "Flask", "GCP", "Git", "GitHub",
    "GitHub Actions", "GitLab CI/CD", "Glide", "Golang", "Google AI Platform",
    "Google Analytics", "Google Tag Manager", "Gradle", "Grafana", "Graylog", "H2O.ai",
    "Hadoop", "Helm", "Heroku", "Hugging Face", "OpenAI API", "IIS", "Informatica",
    "Insomnia", "IntelliJ IDEA", "iOS SDK", "Istio", "Jenkins", "Jenkins X", "JIRA",
    "JMeter", "Jupyter", "Jupyter Notebook", "JUnit", "Kali Linux", "Keras", "Kibana",
    "KNIME", "Kotlin", "Kubernetes", "Lambda", "Linux", "Logstash", "Looker", "LookML",
    "Lucidchart", "MATLAB", "Maven", "Metasploit", "Cognitive Services",
    "Minitab", "MongoDB", "MongoDB Atlas", "Mocha", "Mulesoft",
    "Nagios", "Netlify", "New Relic", "Nexus", "Nginx", "Node.js", "Notion", "NumPy",
    "Objective-C", "OpenCV", "OpenShift", "OpenStack", "Oracle", "Oracle Cloud",
    "Pandas", "Palo Alto Networks", "PeopleSoft", "Podman", "PostgreSQL", "Power BI",
    "Power Automate", "PowerApps", "PowerShell", "Presto", "Prometheus", "Puppet",
    "PyCharm", "Python", "Pytest", "PyTorch", "QlikView", "Qlik Sense", "R", "R Studio",
    "Rancher", "RapidMiner", "React", "Red Hat Enterprise Linux", "Redshift",
    "Retrofit", "Ruby", "RxJava", "Rust", "SalesForce", "SAP", "SAP Analytics Cloud",
    "Scala", "Scikit-learn", "SciPy", "Selenium", "Snyk", "Snowflake", "Spark",
    "Splunk", "Spyder", "SQLite", "SSH", "SQL", "SSL", "Stata", "Superset", "Swagger",
    "Swift", "Tableau", "Tableau Prep", "Tailwind CSS", "Talend", "TensorFlow",
    "Terraform", "Trello", "Travis CI", "Unity", "Unreal Engine", "Vercel",
    "Visual Studio", "VS Code", "Vue.js", "Wireshark", "Windows Server", "Xcode",
    "ASP.NET", "Java", "Spring", "JavaScript", "Angular", "Vue.js", "Ruby on Rails",
    "Laravel", "Gin", "Qt", "SwiftUI", "Android SDK", "TypeScript", "NestJS",
    "Shiny", "Elixir", "Phoenix", "Clojure", "Compojure", "Rocket",
    "Dart", "Flutter", "Haskell", "Yesod", "Julia", "HTTP.jl", "Lua", "LÖVE",
    "Shell", "PowerShell", "Cocoa", "Simulink", "Assembly", "NASM", "COBOL",
    "Pascal", "Free Pascal", "F#", "ASP.NET Core", "Blazor", "Android Studio",
    "Charles Proxy", "PHP", "MySQL", "PHP7", "RabbitMQ", "GitHub", "Agile",
    "Word", "Excel", "PowerPoint",
    "Adobe Creative Suite", "Midjourney", "DALL·E", "Bitrix",
    "Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "CorelDRAW",
    "Midjourney", "DALL·E", "Canva", "Affinity Designer", "Procreate",
    "Font Awesome", "Google Fonts", "DaFont", "Placeit", "MockupWorld"
]
